// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyYouthFutures.Data;
using System;

namespace MyYouthFutures.Migrations
{
    [DbContext(typeof(YouthContext))]
    partial class YouthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyYouthFutures.Models.Doners", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Doner_Name");

                    b.Property<string>("Doner_Type");

                    b.Property<string>("Doner_year");

                    b.HasKey("ID");

                    b.ToTable("Doners");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Entities.StoreUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("StoreUser");
                });

            modelBuilder.Entity("MyYouthFutures.Models.FirstYear_Service_Messages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("firstYearImage");

                    b.Property<string>("firstYearText");

                    b.HasKey("ID");

                    b.ToTable("FirstYear_Service_Message");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Founder_Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("founderImage");

                    b.Property<string>("founderSubTetxt");

                    b.HasKey("ID");

                    b.ToTable("Founder_Message");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Help_Panel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content_Text");

                    b.Property<string>("Content_Type");

                    b.HasKey("ID");

                    b.ToTable("Help_Panel");
                });

            modelBuilder.Entity("MyYouthFutures.Models.HomeTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackgroundImage");

                    b.Property<string>("SubheaderContent");

                    b.Property<string>("Subtitle");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("HomeTitle");
                });

            modelBuilder.Entity("MyYouthFutures.Models.introArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArticleText");

                    b.HasKey("ID");

                    b.ToTable("introArticle");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hyperlink");

                    b.Property<string>("Image");

                    b.Property<string>("Message");

                    b.Property<string>("Title");

                    b.HasKey("LinkID");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("MyYouthFutures.Models.List_Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LiText");

                    b.Property<string>("TypeOfList");

                    b.HasKey("ID");

                    b.ToTable("List_Item");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content_Text");

                    b.Property<string>("Text_Type");

                    b.HasKey("ID");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Purpose", b =>
                {
                    b.Property<int>("PurposeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackgroundImage");

                    b.Property<string>("Content");

                    b.Property<string>("Message");

                    b.Property<string>("Title");

                    b.HasKey("PurposeID");

                    b.ToTable("Purpose");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Services", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Header");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Services_Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.Property<string>("Message");

                    b.Property<string>("MessageHeader");

                    b.Property<string>("MessageImage");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Services_Message");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Staff_Panel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Director");

                    b.Property<string>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Postion");

                    b.Property<string>("Staff_Image");

                    b.Property<string>("email");

                    b.HasKey("ID");

                    b.ToTable("Staff_Panel");
                });

            modelBuilder.Entity("MyYouthFutures.Models.Services_Message", b =>
                {
                    b.HasOne("MyYouthFutures.Models.Entities.StoreUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
